// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prova.Data.Context;

#nullable disable

namespace Prova.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717231039_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prova.Model.Entities.Carne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Origem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carnes", (string)null);
                });

            modelBuilder.Entity("Prova.Model.Entities.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Cidades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoId = 1,
                            Nome = "São Paulo"
                        },
                        new
                        {
                            Id = 2,
                            EstadoId = 1,
                            Nome = "Campinas"
                        },
                        new
                        {
                            Id = 3,
                            EstadoId = 1,
                            Nome = "Guarulhos"
                        },
                        new
                        {
                            Id = 4,
                            EstadoId = 2,
                            Nome = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 5,
                            EstadoId = 2,
                            Nome = "Niterói"
                        },
                        new
                        {
                            Id = 6,
                            EstadoId = 3,
                            Nome = "Belo Horizonte"
                        },
                        new
                        {
                            Id = 7,
                            EstadoId = 3,
                            Nome = "Uberlândia"
                        },
                        new
                        {
                            Id = 8,
                            EstadoId = 4,
                            Nome = "Porto Alegre"
                        },
                        new
                        {
                            Id = 9,
                            EstadoId = 5,
                            Nome = "Curitiba"
                        },
                        new
                        {
                            Id = 10,
                            EstadoId = 6,
                            Nome = "Salvador"
                        },
                        new
                        {
                            Id = 11,
                            EstadoId = 7,
                            Nome = "Brasília"
                        },
                        new
                        {
                            Id = 12,
                            EstadoId = 8,
                            Nome = "Florianópolis"
                        },
                        new
                        {
                            Id = 13,
                            EstadoId = 9,
                            Nome = "Recife"
                        },
                        new
                        {
                            Id = 14,
                            EstadoId = 10,
                            Nome = "Fortaleza"
                        },
                        new
                        {
                            Id = 15,
                            EstadoId = 11,
                            Nome = "Goiânia"
                        },
                        new
                        {
                            Id = 16,
                            EstadoId = 12,
                            Nome = "Vitória"
                        },
                        new
                        {
                            Id = 17,
                            EstadoId = 13,
                            Nome = "Belém"
                        },
                        new
                        {
                            Id = 18,
                            EstadoId = 14,
                            Nome = "Manaus"
                        },
                        new
                        {
                            Id = 19,
                            EstadoId = 15,
                            Nome = "Cuiabá"
                        },
                        new
                        {
                            Id = 20,
                            EstadoId = 16,
                            Nome = "Campo Grande"
                        },
                        new
                        {
                            Id = 21,
                            EstadoId = 17,
                            Nome = "São Luís"
                        },
                        new
                        {
                            Id = 22,
                            EstadoId = 18,
                            Nome = "João Pessoa"
                        },
                        new
                        {
                            Id = 23,
                            EstadoId = 19,
                            Nome = "Natal"
                        },
                        new
                        {
                            Id = 24,
                            EstadoId = 20,
                            Nome = "Maceió"
                        },
                        new
                        {
                            Id = 25,
                            EstadoId = 21,
                            Nome = "Aracaju"
                        },
                        new
                        {
                            Id = 26,
                            EstadoId = 22,
                            Nome = "Teresina"
                        },
                        new
                        {
                            Id = 27,
                            EstadoId = 23,
                            Nome = "Palmas"
                        },
                        new
                        {
                            Id = 28,
                            EstadoId = 24,
                            Nome = "Porto Velho"
                        },
                        new
                        {
                            Id = 29,
                            EstadoId = 25,
                            Nome = "Boa Vista"
                        },
                        new
                        {
                            Id = 30,
                            EstadoId = 26,
                            Nome = "Rio Branco"
                        },
                        new
                        {
                            Id = 31,
                            EstadoId = 27,
                            Nome = "Macapá"
                        });
                });

            modelBuilder.Entity("Prova.Model.Entities.Comprador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("Compradores", (string)null);
                });

            modelBuilder.Entity("Prova.Model.Entities.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Estados", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "São Paulo",
                            Uf = "SP"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Rio de Janeiro",
                            Uf = "RJ"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Minas Gerais",
                            Uf = "MG"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Rio Grande do Sul",
                            Uf = "RS"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Paraná",
                            Uf = "PR"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Bahia",
                            Uf = "BA"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Distrito Federal",
                            Uf = "DF"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Santa Catarina",
                            Uf = "SC"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Pernambuco",
                            Uf = "PE"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Ceará",
                            Uf = "CE"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Goiás",
                            Uf = "GO"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Espírito Santo",
                            Uf = "ES"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Pará",
                            Uf = "PA"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Amazonas",
                            Uf = "AM"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Mato Grosso",
                            Uf = "MT"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Mato Grosso do Sul",
                            Uf = "MS"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Maranhão",
                            Uf = "MA"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Paraíba",
                            Uf = "PB"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Rio Grande do Norte",
                            Uf = "RN"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Alagoas",
                            Uf = "AL"
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Sergipe",
                            Uf = "SE"
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Piauí",
                            Uf = "PI"
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Tocantins",
                            Uf = "TO"
                        },
                        new
                        {
                            Id = 24,
                            Nome = "Rondônia",
                            Uf = "RO"
                        },
                        new
                        {
                            Id = 25,
                            Nome = "Roraima",
                            Uf = "RR"
                        },
                        new
                        {
                            Id = 26,
                            Nome = "Acre",
                            Uf = "AC"
                        },
                        new
                        {
                            Id = 27,
                            Nome = "Amapá",
                            Uf = "AP"
                        });
                });

            modelBuilder.Entity("Prova.Model.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("Prova.Model.Entities.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarneId")
                        .HasColumnType("int");

                    b.Property<decimal>("CotacaoUsada")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("Moeda")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarneId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItens", (string)null);
                });

            modelBuilder.Entity("Prova.Model.Entities.Cidade", b =>
                {
                    b.HasOne("Prova.Model.Entities.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Prova.Model.Entities.Comprador", b =>
                {
                    b.HasOne("Prova.Model.Entities.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("Prova.Model.Entities.Pedido", b =>
                {
                    b.HasOne("Prova.Model.Entities.Comprador", "Comprador")
                        .WithMany("Pedidos")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");
                });

            modelBuilder.Entity("Prova.Model.Entities.PedidoItem", b =>
                {
                    b.HasOne("Prova.Model.Entities.Carne", "Carne")
                        .WithMany("PedidoItens")
                        .HasForeignKey("CarneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Prova.Model.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carne");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Prova.Model.Entities.Carne", b =>
                {
                    b.Navigation("PedidoItens");
                });

            modelBuilder.Entity("Prova.Model.Entities.Comprador", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Prova.Model.Entities.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("Prova.Model.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
